activemq:
  broker-url: tcp://localhost:61616
  user: admin
  password: admin

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#        requestInterceptors: com.baeldung.cloud.openfeign.JSONPlaceHolderInterceptor

server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
              client-secret: cYunCGV91wrv7KI2M3a31LxS

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB