spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS

          github:
            client-id: ce89d42158976382da5d
            client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9

#security:
#  oauth2:
#    google:
#      client:
#        clientId: 182055753030-j95d3j8gp033un6q3rsm1i0j5u31bi09.apps.googleusercontent.com
#        clientSecret: iAbNkjR8JR-FF05BJYj5wMLq
#        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#        scope:
#          -  email
#          -  profile
#      resource:
#        userInfoUri: https://www.googleapis.com/userinfo/v2/me
#        preferTokenInfo: false
