#server:
#  port: 8081
#  servlet:
#    context-path: /auth-service

spring:
  application:
    name: auth-service

  cloud:
    config:
      fail-fast: true
#      uri: http://config:8888

#  datasource:
#    url: jdbc:mysql://localhost:3306/auth_service?useUnicode=true&serverTimezone=UTC
#    username: root
#    password: root
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: false
#    hibernate.ddl-auto: update
#
#  security:
#     oauth2:
#       client:
#         registration:
#           github:
#             client-id: ce89d42158976382da5d
#             client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9
#           google:
#             client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
#             client-secret: cYunCGV91wrv7KI2M3a31LxS

