#  activemq:
#      broker-url: tcp://localhost:61616
#      user: admin
#      password: admin

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#        requestInterceptors: com.baeldung.cloud.openfeign.JSONPlaceHolderInterceptor

server:
  port: 8080
  servlet:
    context-path: /

s3:
  accessKey: AKIAJWCFBXUCARGICLTQ
  secretKey: hJHb2Smt5ByRGeBKnOtIYD8PnR8yd/rFgl2iNZgb
  bucketName: your-bucket-name
  defaultFolder: /Java/temp

fs:
  defaultFolder: /Java/files

conversion:
  defaultFolder: /Java/temp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update

#  elasticsearch:
#    rest:
#      uris:
#      username:
#      password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

cloud:
  aws:
    region: eu-west-1
    credentials:
      accessKey: AKIAJWCFBXUCARGICLTQ
      secretKey: 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
