spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ce89d42158976382da5d
            client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#        requestInterceptors: com.baeldung.cloud.openfeign.JSONPlaceHolderInterceptor

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/users/current
