#server:
#  port: 8084
#  servlet:
#    context-path: /conversion-service
#
#conversion:
#  defaultFolder: /Java/temp

spring:
  application:
    name: conversion-service

  cloud:
    config:
    fail-fast: true
  #      uri: http://config:8888

#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 500MB
#      max-request-size: 500MB
#
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#    packages:
#      trust-all: true