#server:
#  port: 8083
#  servlet:
#    context-path: /user-service

spring:
  application:
    name: user-service

  cloud:
    config:
      fail-fast: true
  #      uri: http://config:8888

#  datasource:
#    url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&serverTimezone=UTC
#    username: root
#    password: root
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: false
#    hibernate.ddl-auto: update
#
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 500MB
#      max-request-size: 500MB