spring:
  security:
    oauth2:
      client:
        registration:
          #          github:
          #            client-id: ce89d42158976382da5d
          #            client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS
      resourceserver:
##        jwt:
##          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs #key-set-uri
##          issuer-uri: https://accounts.google.com
##          public-key-location: classpath:public key.txt #key-value
#  google not support introspection uri
#        opaquetoken:
#          client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
#          client-secret: cYunCGV91wrv7KI2M3a31LxS
#          introspection-uri: https://oauth2.googleapis.com/tokeninfo #post request with map & value token - don't work

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

security:
  oauth2:
    client:
      clientId: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
      clientSecret: cYunCGV91wrv7KI2M3a31LxS
    resource:
#      jwk:
#        key-set-uri: https://www.googleapis.com/oauth2/v3/certs # get JWK & verify the JWT in the Resource Service
#      jwt:
#        key-uri: https://oauth2.googleapis.com/token # or token-info-uri # get JWK & verify the JWT in the Resource Service
#        key-value: # get JWK & verify the JWT in the Resource Service
#      token-info-uri: https://oauth2.googleapis.com/tokeninfo
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo  # info about auth user

logging:
  level:
    com.netflix.eureka: 'OFF'
    com.netflix.discovery: 'OFF'

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 160000000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#dashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

s3:
  defaultBucket: files
  tempBucket: temp

fs:
  defaultFolder: /Java/files
  tempFolder: /Java/temp

