server:
  port: 0 # We can let Spring Boot choose a random port for us because later we are accessing this service with its name.
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/auth_service?useUnicode=true&serverTimezone=UTC}
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update
