server:
#  port: 8084
  port: 0
  servlet:
    context-path: /

conversion:
  defaultFolder: /Java/temp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/song_service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update

cloud:
  aws:
    region: eu-west-1
    credentials:
      accessKey: AKIAJWCFBXUCARGICLTQ
      secretKey: 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