server:
  port: 8084
  servlet:
    context-path: /

conversion:
  defaultFolder: /Java/temp

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB