server:
  port: 8080
  servlet:
    context-path: /

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /auth-service/**
      url: http://localhost:8081
      serviceId: auth-service
      stripPrefix: false
    song-service:
      path: /song-service/**
      url: http://localhost:8082
      serviceId: song-service
      stripPrefix: false
    user-service:
      path: /user-service/**
      url: http://localhost:8083
      serviceId: user-service
      stripPrefix: false
    conversion-service:
      path: /conversion-service/**
      url: http://localhost:8084
      serviceId: conversion-service
      stripPrefix: false
    index-service:
      path: /index-service/**
      url: http://localhost:8085
      serviceId: index-service
      stripPrefix: false

    discovery:
      path: /discovery-service/**
      url: http://localhost:8761
      serviceId: discovery-service
      stripPrefix: false

ribbon:
  eureka:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
#          github:
#            client-id: ce89d42158976382da5d
#            client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS