server:
  port: 8080
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS
#            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
#      stripPrefix: false # Удалять префикс - нужно сохранять path: /auth-service/ если context-path равен /auth-service
    song-service:
      path: /song-service/**
      serviceId: song-service
    play-service:
      path: /play-service/**
      serviceId: play-service
    conversion-service:
      path: /conversion-service/**
      serviceId: conversion-service
    search-service:
      path: /search-service/**
      serviceId: search-service
    storage-service:
      path: /storage-service/**
      serviceId: storage-service
    ui:
      path: /ui/**
      serviceId: ui