server:
  port: 8080
  servlet:
    context-path: /

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
#      url: http://localhost:8081 # Местоположение сервиса может быть указано либо как serviceId, либо как URL
#      stripPrefix: false # Удалять префикс - нужно сохранять path: /auth-service/ если context-path равен /auth-service
    song-service:
      path: /song-service/**
      serviceId: song-service
#      url: http://localhost:8082
#      stripPrefix: false
    play-service:
      path: /play-service/**
      serviceId: play-service
#      url: http://localhost:8083
#      stripPrefix: false
    conversion-service:
      path: /conversion-service/**
      serviceId: conversion-service
#      url: http://localhost:8084
#      stripPrefix: false
    search-service:
      path: /search-service/**
      serviceId: search-service
#      url: http://localhost:8085
#      stripPrefix: false
    storage-service:
      path: /storage-service/**
      serviceId: storage-service
#      url: http://localhost:8086
#      stripPrefix: false