server:
  port: 8080
  servlet:
    context-path: /

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
#      url: http://localhost:8081 # Местоположение сервиса может быть указано либо как serviceId, либо как URL
#      stripPrefix: false # Удалять префикс - нужно сохранять path: /auth-service/ если context-path равен /auth-service
    song-service:
      path: /song-service/**
      serviceId: song-service
#      url: http://localhost:8082
#      stripPrefix: false
    play-service:
      path: /play-service/**
      serviceId: play-service
#      url: http://localhost:8083
#      stripPrefix: false
    conversion-service:
      path: /conversion-service/**
      serviceId: conversion-service
#      url: http://localhost:8084
#      stripPrefix: false
    index-service:
      path: /index-service/**
      serviceId: index-service
#      url: http://localhost:8085
#      stripPrefix: false

#move to app
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
##          github:
##            client-id: ce89d42158976382da5d
##            client-secret: 3ce85c167dc11f88110d23de46c38c254cdd38d9
#          google:
#            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
#            client-secret: cYunCGV91wrv7KI2M3a31LxS