server:
#  port: 8083
  port: 0
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/play_service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update