server:
#  port: 8082
  port: 0
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/song_service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update