server:
  port: 8083
  servlet:
    context-path: /

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#        requestInterceptors: com.baeldung.cloud.openfeign.JSONPlaceHolderInterceptor

s3:
  accessKey: AKIAJWCFBXUCARGICLTQ
  secretKey: hJHb2Smt5ByRGeBKnOtIYD8PnR8yd/rFgl2iNZgb
  bucketName: your-bucket-name
  defaultFolder: /Java/temp

fs:
  defaultFolder: /Java/files

conversion:
  defaultFolder: /Java/temp

spring:
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
  #            client-secret: cYunCGV91wrv7KI2M3a31LxS

  datasource:
    url: jdbc:mysql://localhost:3306/song_service?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate.ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true


cloud:
  aws:
    region: eu-west-1
    credentials:
      accessKey: AKIAJWCFBXUCARGICLTQ
      secretKey: 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

