spring:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696075587142-1aoemai0pdblm3tdqqujkm9blo4h1eoi.apps.googleusercontent.com
            client-secret: cYunCGV91wrv7KI2M3a31LxS

  activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin


