server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0